/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beelbalam1;

import java.awt.event.ItemEvent;
import javax.swing.*;
import java.sql.*;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Itzel Cabrera
 */
public class Window extends javax.swing.JPanel {

    ComboBoxModel EnumSt;
    ComboBoxModel EnumFi;
    
    String user; //usuario con el que se inició sesión
    String oldTarjeta;
    
    Connection conex;
    CallableStatement stm;
    ResultSet rs;
    
    public static PantallaInicio3 p3 = new PantallaInicio3();
    /**
     * Creates new form Window
     */
    //PanelCompras2 pc2;
    
    public Window() {
        initComponents();
        this.btnSaveChanges.setVisible(false);
        this.txtDNombreUsuario.setEditable(false);
        this.txtDCorreoE.setEditable(false);
        this.txtDNumCel.setEditable(false);
        this.txtDNumTarjeta.setEditable(false);
        this.txtDPtosAcum.setEditable(false);
        this.txtDPassword.setEditable(false);
        
        DefaultTableModel modelo = (DefaultTableModel)tabla2.getModel();
        modelo.addColumn("ID Reserva");
        modelo.addColumn("Cliente");
        modelo.addColumn("Fecha");
        //modelo.addColumn("Hora");
        modelo.addColumn("Tramo");  
        modelo.addColumn("Est Inicial");  
        modelo.addColumn("Est Final");  
        modelo.addColumn("Costo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnAcuerdo = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnEdit = new javax.swing.JButton();
        btnSaveChanges = new javax.swing.JButton();
        txtDNombreUsuario = new javax.swing.JTextField();
        txtDCorreoE = new javax.swing.JTextField();
        txtDNumCel = new javax.swing.JTextField();
        txtDPtosAcum = new javax.swing.JTextField();
        txtDNumTarjeta = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        txtDPassword = new javax.swing.JTextField();
        btnEliminarUsuario = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cbTramo = new javax.swing.JComboBox<>();
        cbEstIni = new javax.swing.JComboBox<>();
        cbEstFin = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla2 = new javax.swing.JTable();
        btnActualizar = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btnCerrarSesion = new javax.swing.JButton();

        jPanel5.setBackground(new java.awt.Color(255, 204, 204));

        jLabel22.setFont(new java.awt.Font("Century Gothic", 3, 24)); // NOI18N
        jLabel22.setText("Aviso de Privacidad");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("El tratamiento de datos personales se realiza de conformidad con lo dispuesto en los artículos 8 de la Ley Or\ngánica de la Administración Pública Federal, (última reforma publicada en el Diario Oficial de la Federación, el\n diecinueve de mayo de dos mil diecisiete), 28, fracción III, del Reglamento de la Oficina de la Presidencia de\n la República (publicado en Diario Oficial de la Federación el nueve de diciembre de dos mil diecinueve), 117, \nfracción V de la Ley Federal de Transparencia y Acceso a la Información Pública (última reforma publicada en\n el Diario Oficial de la Federación el veintisiete de enero de dos mil diecisiete), 22, fracción II, 24, 28, 66, fra\ncción I, 69 y 70, fracción II de la Ley General de Protección de Datos Personales en Posesión de Sujetos Obli\ngados.");
        jScrollPane2.setViewportView(jTextArea1);

        btnAcuerdo.setText("Estoy de acuerdo");
        btnAcuerdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcuerdoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAcuerdo)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(255, 255, 255)
                            .addComponent(jLabel22))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGap(122, 122, 122)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAcuerdo)
                .addContainerGap(108, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Aviso Privacidad", jPanel5);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("DATOS DEL PERFIL");

        jLabel1.setText("NOMBRE USUARIO:");

        jLabel3.setText("CORREO ELECTRÓNICO:");

        jLabel4.setText("NÚMERO DE CELULAR:");

        jLabel5.setText("PUNTOS ACUMULADOS:");

        jLabel6.setText("NÚMERO DE TARJETA: ");

        btnEdit.setText("Editar");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnSaveChanges.setText("Guardar Cambios");
        btnSaveChanges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveChangesActionPerformed(evt);
            }
        });

        txtDNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDNombreUsuarioActionPerformed(evt);
            }
        });

        jLabel21.setText("CONTRASEÑA:");

        btnEliminarUsuario.setText("Eliminar Usuario");
        btnEliminarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUsuarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(175, 175, 175)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnEliminarUsuario)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6)
                                .addComponent(jLabel21))
                            .addGap(39, 39, 39)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnSaveChanges))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtDPassword, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDCorreoE, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDNombreUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDNumCel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDPtosAcum, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDNumTarjeta, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDNombreUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDCorreoE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDNumCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDPtosAcum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtDNumTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel21)
                    .addComponent(txtDPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnSaveChanges, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarUsuario)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver Perfil", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 153, 204));

        jButton1.setText("Vas Toñito");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Garamond", 3, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 255, 204));
        jLabel7.setText("Bienvenido");

        jLabel9.setText("TRAMO:");

        jLabel10.setText("ESTACIÓN INICIAL:");

        jLabel11.setText("ESTACIÓN FINAL:");

        jLabel12.setText("NOMBRE PASAJERO:");

        jLabel13.setText("NOMBRE/S");

        jLabel14.setText("APELLIDO PATERNO");

        jLabel15.setText("APELLIDO MATERNO");

        jLabel16.setText("EDAD:");

        jLabel17.setText("PAIS DE ORIGEN:");

        cbTramo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "SELVA 1", "SELVA 2", "GOLFO 1", "GOLFO 2", "CARIBE 1", "CARIBE 2" }));
        cbTramo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbTramoItemStateChanged(evt);
            }
        });
        cbTramo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbTramoActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        jLabel18.setText("DÍA:");

        jLabel19.setText("MES:");

        jLabel20.setText("AÑO:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(cbEstIni, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(106, 106, 106)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbEstFin, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(cbTramo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(112, 112, 112)
                                                .addComponent(jLabel18)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(jLabel7))
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel20)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(jButton1)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel14))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(46, 46, 46)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel7)
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cbTramo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(cbEstIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEstFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel13))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15))))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addGap(89, 89, 89))
        );

        jTabbedPane1.addTab("Comprar Boleto", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 153, 0));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Historial de compras"));

        tabla2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabla2);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(50, Short.MAX_VALUE))
        );

        btnActualizar.setText("Actualizar data");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnActualizar)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(btnActualizar)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ver Historial", jPanel3);

        jPanel4.setBackground(new java.awt.Color(204, 0, 204));

        btnCerrarSesion.setText("CerrarSesion");
        btnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(324, 324, 324)
                .addComponent(btnCerrarSesion)
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(btnCerrarSesion)
                .addContainerGap(168, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cerrar Sesion", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    public void cbLlenarV(String datos){
        if(datos.equalsIgnoreCase("SELVA 1")){
            this.EnumSt = new DefaultComboBoxModel(TSelva1.values());
            this.EnumFi = new DefaultComboBoxModel(TSelva1.values());
        }else if (datos.equalsIgnoreCase("SELVA 2")){
            this.EnumSt = new DefaultComboBoxModel(TSelva2.values());
            this.EnumFi = new DefaultComboBoxModel(TSelva2.values());
        }else if(datos.equalsIgnoreCase("GOLFO 1")){
            this.EnumSt = new DefaultComboBoxModel(TGolfo1.values());
            this.EnumFi = new DefaultComboBoxModel(TGolfo1.values());
        }else if(datos.equalsIgnoreCase("GOLFO 2")){
            this.EnumSt = new DefaultComboBoxModel(TGolfo2.values());
            this.EnumFi = new DefaultComboBoxModel(TGolfo2.values());
        }else if(datos.equalsIgnoreCase("CARIBE 1")){
            this.EnumSt = new DefaultComboBoxModel(TCaribe1.values());
            this.EnumFi = new DefaultComboBoxModel(TCaribe1.values());
        }else if(datos.equalsIgnoreCase("CARIBE 2")){
            this.EnumSt = new DefaultComboBoxModel(TCaribe2.values());
            this.EnumFi = new DefaultComboBoxModel(TCaribe2.values());
        }
    }
    private void btnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesionActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarSesionActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        oldTarjeta = this.txtDNumTarjeta.getText();
        this.btnEdit.setVisible(false);
        this.btnSaveChanges.setVisible(true);
        this.txtDNombreUsuario.setEditable(true);
        this.txtDCorreoE.setEditable(true);
        this.txtDNumCel.setEditable(true);
        this.txtDNumTarjeta.setEditable(true);
        this.txtDPassword.setEditable(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveChangesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveChangesActionPerformed
        String u = null;
        //Datos por la psoible insercion de una tarjeta
        int cvc;
        String pN;
        String sN;
        String pA;
        String sA;
        int fecha;
        String[] list = {"No","Si"};
        JComboBox jcb = new JComboBox(list);
        jcb.setVisible(false);
        
        if(this.txtDNumTarjeta.getText().equals(oldTarjeta)){//no se cambbiará la tarjeta
            u = this.editUsuario();
            this.changes(u);
        }else{//se quiere cambiar la tarjeta
            String r = null;
            try {
                //Conecta
                conex = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-KT6L84G:1433;databaseName=BEEL_BALAM", "sa", "2020640576");
                //Busca si la tarjeta ya existe
                stm = conex.prepareCall("{call CHECK_TARJETA(?)}");
                stm.setString(1, this.txtDNumTarjeta.getText());
                rs = stm.executeQuery();
                if(rs.next())r = rs.getString(1);
                if(r.equals("E")){//ya existe la tarjeta--> se aplica un editUsuario()
                    u = this.editUsuario();
                }else{ //no existe la tarjeta, se deben agregar sus datos
                    cvc = Integer.parseInt(JOptionPane.showInputDialog("Inserte el CVC"));
                    fecha = Integer.parseInt(JOptionPane.showInputDialog("Inserte la fecha de vigencia [MMAA]"));
                    pN = JOptionPane.showInputDialog("Inserte el primer nombre del representante");
                    jcb.setVisible(true);
                    jcb.setEditable(true);
                    JOptionPane.showMessageDialog(null,jcb,"¿El representante tiene segundo nombre?",JOptionPane.QUESTION_MESSAGE);
                    String opc = (String) jcb.getSelectedItem();
                    if(opc.equals("Si"))sN = JOptionPane.showInputDialog("Inserte el segundo nombre del representante");
                    else sN = null;
                    pA = JOptionPane.showInputDialog("Inserte el primer apellido del representante");
                    JOptionPane.showMessageDialog(null,jcb,"¿El representante tiene segundo apellido?",JOptionPane.QUESTION_MESSAGE);
                    String opc2 = (String) jcb.getSelectedItem();
                    if(opc2.equals("Si"))sA = JOptionPane.showInputDialog("Inserte el segundo apellido del representante");
                    else sA = null;
                    u = this.editUsuario(cvc,fecha,pN,sN,pA,sA);
                }
                this.changes(u);
            } catch (SQLException ex) {
                System.out.println("ERROR en saveChanges");
            }
        }
        this.btnEdit.setVisible(true);
    }//GEN-LAST:event_btnSaveChangesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtDNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDNombreUsuarioActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void cbTramoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbTramoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbTramoActionPerformed

    private void cbTramoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbTramoItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED){
            if(this.cbTramo.getSelectedIndex()>0){
                cbLlenarV(this.cbTramo.getSelectedItem().toString());
                this.cbEstIni.setModel(this.EnumSt);
                this.cbEstFin.setModel(this.EnumFi);
            }
        }
    }//GEN-LAST:event_cbTramoItemStateChanged

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void btnAcuerdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcuerdoActionPerformed
        //Manda la info al panel "VerPerfil"
        String u = this.getUser();
        this.getData(u,1);
        this.btnEdit.setVisible(true);
    }//GEN-LAST:event_btnAcuerdoActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        for(int i = 0; i<((DefaultTableModel)tabla2.getModel()).getRowCount();i++){
             ((DefaultTableModel)tabla2.getModel()).removeRow(i);
        }
        try{
            Connection miConexion = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-KT6L84G:1433;databaseName=BEEL_BALAM", "sa", "2020640576");
            CallableStatement resConexion;
            resConexion = miConexion.prepareCall("{call VER_HISTORIAL_COMPRAS(?)}");
            //System.out.println("nUsuario en window: "+nUsuario);
            //System.out.println("nUsuarioPI en window: "+p3.nUsuarioPI);
            resConexion.setString(1,p3.nUsuarioPI);

            ResultSet rs = resConexion.executeQuery();
            while(rs.next()){
                //Object fila[] = {"20","anita","10/20/20","selva","tulum","escarcega",100};
                String nombre = rs.getString(2)+" "+rs.getString(3)+" "+rs.getString(4)+" "+
                        rs.getString(5);
                Object fila[] = {rs.getInt(1),nombre,rs.getDate(6),rs.getString(7),
                    rs.getString(8),rs.getString(9),rs.getDouble(10)};
                ((DefaultTableModel)tabla2.getModel()).addRow(fila);
            }
            rs.close();
        }catch(Exception e){
            //System.out.println("Ha habido un error al crear al usuario");
            System.out.println(e);
        }
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnEliminarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUsuarioActionPerformed
        ProcEliminarUsuario procElimU = new ProcEliminarUsuario();
        procElimU.setNombreBU(txtDNombreUsuario.getText());
        procElimU.setTarjetaBU(txtDNumTarjeta.getText());
        
        String ans[] = {"Eliminar","Cancelar"}; 
        int opc = JOptionPane.showOptionDialog(this,"¿Desea eliminar de manera permanente su cuenta de usuario?", 
                "Confirmar elimnar usuario", 0, 0, null,ans,this);
        if(opc == JOptionPane.YES_OPTION){
            procElimU.hacerConexionBUsuario();
            System.out.println("Después de hacer conexion");
            
           System.exit(0); 
        }
    }//GEN-LAST:event_btnEliminarUsuarioActionPerformed

    public void changes(String u){
        //Metodo que manda la info de los cambios hechos en los datos del usuario
        this.btnSaveChanges.setVisible(false);
        this.txtDNombreUsuario.setEditable(false);
        this.txtDCorreoE.setEditable(false);
        this.txtDNumCel.setEditable(false);
        this.txtDNumTarjeta.setEditable(false);
        this.txtDPassword.setEditable(false);

        System.out.println(u);
        if(u.equals("SC")){ //sin cambios en el nombre del usuario
            this.getData(this.getUser(),2);
            JOptionPane.showMessageDialog(null, "Sin cambios en el nombre del usuario");
        }
        else if(u.equals("UYE")) {//no se cambia el usuario, porque ya existe
            JOptionPane.showMessageDialog(null, "Usuario no válido");
            this.getData(this.getUser(),2);
        }
        else {//se cambió el usuario
            JOptionPane.showMessageDialog(null, "Usuario cambiado con exito");
            this.setUser(u);
            this.getData(u,2);
        }

        System.out.println("Usuario = "+this.user);
    }
    
    public void setUser(String u){
        //Metodo que cambia el usuario en sesion
        this.user = u;
    }
    
    public String getUser(){
        //Metodo que obtiene el usuario en sesion
        return this.user;
    }

    public void getData(String user,int n){
        //Metodo que obtiene la data del usuario 
        String nombre = null;
        String contra = null;
        String correo = null;
        String numero = null;
        String tarjeta = null;
        int ptos = 0;
        try {
            //Conecta
            conex = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-KT6L84G:1433;databaseName=BEEL_BALAM", "sa", "2020640576");
            //Obtiene la info del usuario
            stm = conex.prepareCall("{call GET_USERDATA(?)}");
            stm.setString(1, user);
            rs = stm.executeQuery();
            if(rs.next()){ //si encuentra el usuario, verifica que la contraseña sea correcta
                nombre = rs.getString(1);
                contra = rs.getString(2);
                correo = rs.getString(3);
                numero = rs.getString(4);
                ptos = rs.getInt(5);
                tarjeta = rs.getString(6);
            }else{
                JOptionPane.showMessageDialog(null, "Usuario no encontrado");
            }
            System.out.println(nombre+"/"+contra+"/"+correo+"/"+numero+"/"+ptos+"/"+tarjeta);
            rs.close();
            stm.close();
            this.txtDNombreUsuario.setText(nombre);
            this.txtDCorreoE.setText(correo);
            this.txtDNumCel.setText(numero);
            this.txtDPtosAcum.setText(Integer.toString(ptos));
            this.txtDNumTarjeta.setText(tarjeta);
            this.txtDPassword.setText(contra);
            
            if(n == 1) this.btnAcuerdo.setVisible(false);
            
        } catch (SQLException ex) {
            System.out.println("ERROR en getData");
        }
    }
    
    public String editUsuario(int cvc,int fecha,String pN,String sN,String pA,String sA){
        //Metodo para editar datos del usuario cuando pretende cambiar la tarjeta
        System.out.println("Agrega una tarjeta");
        String r = null;
        try {
            //Conecta
            conex = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-KT6L84G:1433;databaseName=BEEL_BALAM", "sa", "2020640576");
            //Inserta la nueva tarjeta
            stm = conex.prepareCall("{call INSERT_TARJETA(?,?,?,?,?,?,?)}");
            stm.setString(1, this.txtDNumTarjeta.getText());
            stm.setInt(2,cvc );
            stm.setString(3,pN );
            stm.setString(4,sN);
            stm.setString(5,pA);
            stm.setString(6,sA);
            stm.setInt(7,fecha);
            rs = stm.executeQuery();
            if(rs.next()){
                r = rs.getString(1);
                System.out.println("RES1 = "+ r);
            }
            stm = conex.prepareCall("{call EDIT_U_COMPLETE(?,?,?,?,?,?)}");
            stm.setString(1, this.getUser());
            stm.setString(2, this.txtDNombreUsuario.getText());
            stm.setString(3, this.txtDPassword.getText());
            stm.setString(4, this.txtDCorreoE.getText());
            stm.setString(5, this.txtDNumCel.getText());
            stm.setString(6, this.txtDNumTarjeta.getText());
            rs = stm.executeQuery();
            if(rs.next()){
                r = rs.getString(1);
                System.out.println("RES = "+ r);
            }
        } catch (SQLException ex) {
            System.out.println("ERROR en editUsuario AGREGARTARJETA");
        }
        
        return r;
    }
    public String editUsuario(){//Metodo para editar datos del usuario cuando no pretende cambiar la tarjeta
        String r = null;
        System.out.println("No se tiene que agregar una tarjeta");
        try {
            //Conecta
            conex = DriverManager.getConnection("jdbc:sqlserver://DESKTOP-KT6L84G:1433;databaseName=BEEL_BALAM", "sa", "2020640576");
            //Cambia los datos, excepto los de la tarjeta
            stm = conex.prepareCall("{call EDIT_U_SIMPLE(?,?,?,?,?,?)}");
            stm.setString(1, this.getUser());
            stm.setString(2, this.txtDNombreUsuario.getText());
            stm.setString(3, this.txtDPassword.getText());
            stm.setString(4, this.txtDCorreoE.getText());
            stm.setString(5, this.txtDNumCel.getText());
            stm.setString(6, this.txtDNumTarjeta.getText());
            rs = stm.executeQuery();
            if(rs.next())r = rs.getString(1);
        } catch (SQLException ex) {
            System.out.println("ERROR en editUsuario");
        }
        return r;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnAcuerdo;
    private javax.swing.JButton btnCerrarSesion;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnSaveChanges;
    private javax.swing.JComboBox<String> cbEstFin;
    private javax.swing.JComboBox<String> cbEstIni;
    private javax.swing.JComboBox<String> cbTramo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTable tabla2;
    private javax.swing.JTextField txtDCorreoE;
    private javax.swing.JTextField txtDNombreUsuario;
    private javax.swing.JTextField txtDNumCel;
    private javax.swing.JTextField txtDNumTarjeta;
    private javax.swing.JTextField txtDPassword;
    private javax.swing.JTextField txtDPtosAcum;
    // End of variables declaration//GEN-END:variables
}
